steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/fulstech/$REPO_NAME:$SHORT_SHA",
        ".",
      ]
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/fulstech/$REPO_NAME:$SHORT_SHA"
timeout: 900s
