steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/stackedit:$SHORT_SHA",
        ".",
      ]
images:
  - "gcr.io/$PROJECT_ID/stackedit:$SHORT_SHA"
timeout: 900s
